---
# tasks file for consul

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: consul

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: consul

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: consul

- name: Download Consul
  get_url: >
    url={{ consul_url }}
    dest={{ consul_download_dir }}/consul.zip
    sha256sum={{ consul_sha256sum }}
  tags: consul

- name: Unzip Consul to installation directory
  command: unzip {{ consul_download_dir }}/consul.zip -d {{ consul_install_dir }}
  args:
    creates: "{{ consul_install_dir }}/consul"
  tags: consul

- name: Create Consul configuration directory
  file: >
    path={{ consul_config_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: consul

- include: webui.yml
  when: consul_webui
  tags:
    - consul
    - consul-webui
